### ISSUE TITLE
column "geom" does not exist

### ISSUE THREAD

**Issue by mixedbredie** [lutraconsulting/qgis-discovery-plugin#1]
Hello,

A quick test of the new search plugin returns the following error:

`    2015-11-17T09:31:52	1	Traceback (most recent call last):
    			  File "C:/Users/me/.qgis2/python/plugins\Discovery\discoveryplugin.py", line 211, in     do_db_operations
    			    self.perform_search()
    			  File "C:/Users/me/.qgis2/python/plugins\Discovery\discoveryplugin.py", line 220, in perform_search
    			    cur.execute(self.query_sql, self.query_dict)
    			ProgrammingError: column "geom" does not exist
    			LINE 3:                         ST_SRID(geom) AS epsg,`

I have configured the plugin to use a `full_address` field in the database table with a geometry column called `geometry` and not `geom`.

The pg_trgm extension is installed and an appropriate index built on the on the `full_address` field.

QGIS 2.12 32bit, PostgreSQL 9.2.13

**Comment by mixedbredie** [comment]
Appears to be line 128 in dbutils.py where the error is occuring.

**Comment by wonder-sk** [comment]
Thanks for the report - should be fixed in 1.0.1 (just uploaded)
