### ISSUE TITLE
Where is the config file saved?

### ISSUE THREAD

**Issue by TimJMartin** [lutraconsulting/qgis-discovery-plugin#23]
Hi

Is the config file saved to the plugin/discovery folder as I cannot find it, or is it saved somewhere else?

Ideally we were hoping to setup multiple configs and then transfer the file to other users.

Thanks in advance

Tim

**Comment by saberraz** [comment]
Hi Tim,

From Discovery page on our website:
https://www.lutraconsulting.co.uk/products/discovery/

_"Windows users' Discovery settings are stored in the Windows registry. In the case of a large QGIS deployment, these registry settings can be packaged with QGIS to 'pre-configure' users' installations."_
