### ISSUE TITLE
password protected connections

### ISSUE THREAD

**Issue by antoniusz** [lutraconsulting/qgis-discovery-plugin#3]
I've got a password (supplied on connect) protected connection, and there is no possibility in the configuration dialog to provide one.

**Comment by klakar** [comment]
Should tie in to the new authentication system if possible, so that no unencrypted passwords are stored anywhere in the system.

**Comment by saberraz** [comment]
Discovery is using connection settings. So, you will need to set it as @klakar suggested and use the connection in the Discovery settings.

**Comment by mixedbredie** [comment]
I know this is closed but I still can't get the plugin to connect using a connection without a saved password OR with a connection saved in the encrypted authentication database.  I get a message in the plugin configuration:

`('fesendauth: no password supplied\n',)`

I'm using the latest version (2.1.1) from the repo.  Maybe I am not using the authentication system correctly?

**Comment by antoniusz** [comment]
Because of this error(?), I could never use the plugin, even though I use the new authentication system.

**Comment by wonder-sk** [comment]
Discovery does not support the new authentication system yet - currently you need to store the password in the connection definition.

**Comment by antoniusz** [comment]
Thank you! Storing the username and password as you suggested, it's working. Thank you again, it's a great plugin.

**Comment by StocktonGIS** [comment]
Thanks guys, I struggled for ages with this too until finding this thread.  The solution is to use a connection with only Basic Authentication.  I have set up a new connection especially for Discovery.  Great plugin now it is working.

**Comment by saberraz** [comment]
This should be supported since 2.3.0
