### ISSUE TITLE
Working with QGIS 3.2?

### ISSUE THREAD

**Issue by StocktonGIS** [lutraconsulting/qgis-discovery-plugin#32]
Have both QGIS 2.18.20 and QGIS  3.2.1 installed on my workstation with same configuration.  Discovery works great with 2.18.20 but not with 3.2.1 .

When setting up configuration get (fe_sendauth;no password supplied\n') and drop downs not populating.  Have checked database connections and all are fine.

**Comment by saberraz** [comment]
Works fine for me in QGIS 3.x
![disco](https://user-images.githubusercontent.com/2649047/43321723-a978eb40-91a4-11e8-9f60-728c129c1fb4.gif)

**Comment by StocktonGIS** [comment]
Great.  Must be a configuration issue then?  Have followed instructions on https://www.lutraconsulting.co.uk/products/discovery/ which may have been designed for an earlier version?  Maybe there is a further step required to define connection parameters?
![discovery configuration 3](https://user-images.githubusercontent.com/41787574/43332102-43c72850-91bf-11e8-8828-3db489752661.jpg)
![discovery configuration 2 18](https://user-images.githubusercontent.com/41787574/43332103-43e124e4-91bf-11e8-9fa7-e32dfbb8c9c3.jpg)
