### ISSUE TITLE
Save Configuration

### ISSUE THREAD

**Issue by fanou77** [lutraconsulting/qgis-discovery-plugin#35]
Can you add the configuration backup so you can import it to another computer?
Thanks,
Stéphane
"Sorry for my bad english"

**Comment by saberraz** [comment]
Hi Stephane,

The configuration file is saved under Windows Registry. So, if you go to QGIS section of your regedit, you should be able to see Discovery plugin configuration.

Cheers
Saber

**Comment by fanou77** [comment]
At work, I'm not an administrator of my computer , so I don't have access to the registry.

Thanks,
Stéphane

**Comment by saberraz** [comment]
You don't need to be admin. you can just run `regedit` from your start menu.
