### ISSUE TITLE
Master download of Discovery

### ISSUE THREAD

**Issue by Simon-Miles-rbwm** [lutraconsulting/qgis-discovery-plugin#51]
I've installed (via a downloaded ZIP of the latest release) Discovery but getting the following error message..

This plugin is broken
Missing metadata file

![image](https://user-images.githubusercontent.com/20357533/53163964-23fc1d80-35c7-11e9-88fb-76d7e829af4e.png)

**Comment by Simon-Miles-rbwm** [comment]
I've now added the Discovery folder from the downloaded Zip into QGIS\QGIS3\profiles\default\python\plugins and the plugin is now open. However I don't see the option  for connecting to a GeoPackage. I do see a message in the bottom of the Connection window.

![image](https://user-images.githubusercontent.com/20357533/53164417-0aa7a100-35c8-11e9-8d78-1257ed0f8d94.png)

**Comment by saberraz** [comment]
You need to unzip and then rezip Discovery folder.
