### ISSUE TITLE
MSSQL Connection showing no results

### ISSUE THREAD

**Issue by mtravis** [lutraconsulting/qgis-discovery-plugin#53]
I've created a MSSQL connection but it doesn't show any results.

![image](https://user-images.githubusercontent.com/1799238/54351641-ce57e580-4647-11e9-9f24-87a6fb20f7e6.png)

But the connection definitely works as I can choose fields, etc 

![image](https://user-images.githubusercontent.com/1799238/54351760-1a0a8f00-4648-11e9-8854-a72b8cc2b0d7.png)

**Comment by saberraz** [comment]
I can confirm in QGIS 3.4.5 and the discovery branch for mssql

**Comment by saberraz** [comment]
Some more infor on the MSSQL and connection settinsg:

- MSSQL version: 2012
- Connection type: trusted (no username and password)

**Comment by mtravis** [comment]
We are using 2012

When I changed to trusted connection I get:

Error opening connection: [Microsoft][ODBC SQL Server Driver][SQL Server]Login failed for user 'DARTMOOR\mtravis'. [Microsoft][ODBC Driver Manager] Driver's SQLSetConnectAttr failed QODBC3: Unable to connect

It won't let use a trusted connection as it uses a specific username and password to connect to the database server.

**Comment by saberraz** [comment]
Got fixed by https://github.com/lutraconsulting/qgis-discovery-plugin/commit/3c8fde5d675b7d89a917f8d5bf4bb72b48917002

**Comment by mtravis** [comment]
Still wasn't working. 
`The concat function requires 2 to 254 arguments. QODBC3: Unable to execute statement`

Fixed by changing: 

`query_text += "CONCAT( %s ) AS suggestion_string" % joined_info_columns`

to 

`query_text += "CONCAT( %s ,'') AS suggestion_string" % joined_info_columns`

Tried to add via PR but wouldn't let me.

**Comment by saberraz** [comment]
@mtravis you can fork the repo first. Clone your forked repo, and then make changes, commit to your forked repo and then a PR.

**Comment by wonder-sk** [comment]
No worries, I will fix this (using slightly different approach) and release a new version

**Comment by mtravis** [comment]
@saberraz will bear that in mind for future 

thanks @wonder-sk

**Comment by wonder-sk** [comment]
Fixed in 2.4.1
