### ISSUE TITLE
Search tables with no geometry

### ISSUE THREAD

**Issue by nicolasmcfadden** [lutraconsulting/qgis-discovery-plugin#55]
Great work with adding Geopackage recently!
However I was wondering if you were planning on making tables with no geometry searchable as well?

**Comment by wonder-sk** [comment]
How would that work though without geometries? The idea of Discovery plugin is to highlight the searched features on the map...

**Comment by nicolasmcfadden** [comment]
That's a fair point so I'll explain why I thought of that.
I have a construction project with a buildings layer (polygon ofc) and a equipment layer (no geometry) bound by a relation to the buildings so for each building I can have the equipment list.
However the "Discovery" plugin is also very handy to quickly type an equipment tag to have basic information appear about it and open it's relevant attribute table.
I've actually been using it that way with an equipment "point layer" but that contains no points and it works ok. But I thought it was kind of convoluted to fake a point layer to be able to use the plugin..

**Comment by saberraz** [comment]
Have you tried Locator toolbar?

**Comment by nicolasmcfadden** [comment]
I just tried and it tells me "no geometry" and it doesn't open the attribute table.
