### ISSUE TITLE
missing dsn and no parameters

### ISSUE THREAD

**Issue by philipjohnbarlow** [lutraconsulting/qgis-discovery-plugin#57]
Discovery can no longer see my database connections and I am seeing an error message in the bottom left of the configuration window that states "missing dsn and no parameters".  Sounds like its ODBC related?

Settings saved from previous versions of the plugin are still in but there are no results from queries entered in the search box.

QGIS version: 3.4.5.1

**Comment by saberraz** [comment]
How do you authenticate with your database? You need to store the password within the connection.

**Comment by glw** [comment]
I was having the same exact issue, I had to go back to "edit connections" and re-save and re-agree to save the stored username and password. Not sure why this worked for me but it did.

**Comment by philipjohnbarlow** [comment]
> How do you authenticate with your database? You need to store the password within the connection.

Hi Saber, apologies for the delay in replying.  I'm just using basic authentication.

glw's solution above hasn't done the trick for me, I'll keep playing around and see if I can get it to pick up my databases.

**Comment by PeterPetrik** [comment]
fixed
