### ISSUE TITLE
Can't select PostgreSQL connection and other oddities)

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/qgis-discovery-plugin#59]
Steps to reproduce:

1. Have a working PostgreSQL connection
2. Open discovery settings
3. Click +
4. Try to select a connection (there's none in the list and there should be)

Workaround (partial):

Now:

5. Change Data source type to GeoPackage and back to PostgreSQL

Drop-down now works as expected.  

However, I now get an error about missing dsn or similar at the bottom and unable to see any schemata in Schema drop-down.

Unfortunately unable to reproduce the missing schema issue reliably on my computer.

**Comment by PeterPetrik** [comment]
fixed
