### ISSUE TITLE
global settings file

### ISSUE THREAD

**Issue by tschuettenberg** [lutraconsulting/qgis-discovery-plugin#72]
(Like all QGIS settings) The Discovery configuations are saved in a QGIS/QGIS3.ini file under the active user profile directory.[1] Now I try to centralise these settings in a Global Settings file[2] on a network shared folder for the QGIS deployment throughout my organisation. 

But if I **move** the Discovery settings from QGIS3.ini to qgis_global_settings.ini Discovery does not see them anymore and the config does not work. 
I'm using command line option --globalsettingsfile and environment variable QGIS_GLOBAL_SETTINGS_FILE and the settigs from my qgis_global_settings.ini show up in the Advanced Settings tab[1] in QGIS options.

So, how can the config be used either (resp. in addition) from a (shared) global settings file or QGIS3.ini?

[1] https://docs.qgis.org/3.10/en/docs/user_manual/introduction/qgis_configuration.html#advanced-settings
[2] https://docs.qgis.org/3.10/en/docs/user_manual/introduction/qgis_configuration.html#running-qgis-with-advanced-settings

**Comment by tschuettenberg** [comment]
Maybe migrating the plugin code from QSettings to QgsSettings??!

https://qgis.org/pyqgis/3.10/core/QgsSettings.html 
https://github.com/qgis/QGIS/pull/4160
...I realy do not understand this great magic, but some web searching led me to this idea. ;-)
would that be feasible?

**Comment by tschuettenberg** [comment]
OK, method trial-and-error: AFAIU (https://github.com/lutraconsulting/qgis-discovery-plugin/issues/72#issuecomment-623975527) the successor for QSettings (throughout the QGIS codebase) is QgsSettings. Therefore I added `from qgis.core import QgsSettings` to config_dialog.py, dbutils.py, discoveryplugin.py & mssql_utils.py and replaced every occurence of QSettings in these files, see  https://github.com/lutraconsulting/qgis-discovery-plugin/compare/master...tschuettenberg:master

And surprise, surprise, it works! :-) Do you want me to make it a PR?

**Comment by saberraz** [comment]
That is great! Could you please do a PR.

Many many thanks!

**Comment by wonder-sk** [comment]
fixed in #73
