### ISSUE TITLE
Not seaching strings properly where they contain spaces

### ISSUE THREAD

**Issue by rugbygis** [lutraconsulting/qgis-discovery-plugin#76]
After last update partial strings result in not seach e.g seaching on postcode CV21 brings back a list of all addresses with that postcode but putting the space after this and then the subsequent text results in nothing e.g CV21 2NY returns no records. Put in "Wood" and all records with the term wood in are returned but add a space and then the term "Street" and no records are returned. However, put in "Street" and all occurencies of street are returned.
I believe that adding a space in the address string stops the search from functioning and where address strings are concerned this is an issue as most address strings have spaces.

**Comment by erpas** [comment]
Confirmed, unfortunatelly... 

@mostlyAtNight , we can either:
1. Remove last changes, or
2. Have the escaping of special characters as an option in the config with default no escaping?

**Comment by rugbygis** [comment]
The purpose of the plugin is to provide an effcient search method for addesses and up until the last release it did this in an efficient and comprehensive manner so was fantastic.  Myself and 2 colleagues from other authorities paid for the development to extend its use with geopackage searching and this went well but this latest version has negated that investment because of the issues I've highlighted.  Address strings will typically contain spaces and other special charactors - hyphens, commas, single quotation marks etc. so these need to be counted as valid parts of a string so escaping special characters would get round that problem and the previous version must have done this. Please could we have a fix a.s.a.p. as this plugin is used extensively within my organisation and I knw, quite a few local authorities within the UK.  Thank you.

**Comment by saberraz** [comment]
Hi @rugbygis 
You can downgrade your plugin:
https://plugins.qgis.org/plugins/Discovery/version/2.4.3/
Download the zip file and install it from the plugin manager.

The issue was introduced in the past couple of months and we will sort out a fix soon.

**Comment by rugbygis** [comment]
Thanks Saber. Helpful as always. Mark P.

**Comment by tschuettenberg** [comment]
My colleage just pointed me to this issue and I tested with the last versions (in QGIS 3.10.7): 
Discovery 2.5.1 works, 2.5.2 and 2.5.3 choke (at least) on space characters.

**Comment by mostlyAtNight** [comment]
Hi @rugbygis and @tschuettenberg ,

This issue should now be resolved in version 2.5.4

The special character escaping is now an option in the configuration that's disabled by default.

Kind regards,

Pete

**Comment by rugbygis** [comment]
Hi Pete. Tested and confirm that it works - thank you.
