### ISSUE TITLE
python invalid syntax error

### ISSUE THREAD

**Issue by glw** [lutraconsulting/qgis-discovery-plugin#79]
The last couple versions Ive been getting a syntax error with the discover plugin. I believe it is because of f-string use which is for python 3.6+. But Im using 3.5. Is is possible to switch back to boring old "format" :)

Here's my error:
Couldn't load plugin 'Discovery' due to an error when calling its classFactory() method 

SyntaxError: invalid syntax 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Discovery/__init__.py", line 15, in classFactory
    from .discoveryplugin import DiscoveryPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Discovery/discoveryplugin.py", line 327
    err_info += f"{e.pgerror}"
                             ^
SyntaxError: invalid syntax

Python version: 3.5.2 (default, Apr 16 2020, 17:47:17) [GCC 5.4.0 20160609] 
QGIS version: 3.4.15-Madeira Madeira, e83d02e274 

Python Path:
/usr/share/qgis/python
/home/user/.local/share/QGIS/QGIS3/profiles/default/python
/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python35.zip
/usr/lib/python3.5
/usr/lib/python3.5/plat-x86_64-linux-gnu
/usr/lib/python3.5/lib-dynload
/home/user/.local/lib/python3.5/site-packages
/usr/local/lib/python3.5/dist-packages
/usr/lib/python3/dist-packages
/home/user/.local/share/QGIS/QGIS3/profiles/default/python

**Comment by erpas** [comment]
Solved in https://github.com/lutraconsulting/qgis-discovery-plugin/pull/81
