### ISSUE TITLE
Couldn't load plugin 'Discovery' 

### ISSUE THREAD

**Issue by antoniusz** [lutraconsulting/qgis-discovery-plugin#89]
I've got this error on starting QGIS 3.29 master

Couldn't load plugin 'Discovery' due to an error when calling its classFactory() method 

TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool' 
Traceback (most recent call last):
  File "/home/toni/.qgis_apps_330/share/qgis/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/toni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Discovery/__init__.py", line 16, in classFactory
    return DiscoveryPlugin(iface)
  File "/home/toni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Discovery/discoveryplugin.py", line 153, in __init__
    self.rubber_band = QgsRubberBand(iface.mapCanvas(), False)
TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool'

Python version: 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] 
QGIS version: 3.29.0-Master Master, ccf1835b6c 

Python Path:
/home/toni/.qgis_apps_330/share/qgis/python
/home/toni/.local/share/QGIS/QGIS3/profiles/default/python
/home/toni/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/home/toni/.qgis_apps_330/share/qgis/python/plugins
/usr/lib/python39.zip
/usr/lib/python3.9
/usr/lib/python3.9/lib-dynload
/home/toni/.local/lib/python3.9/site-packages
/usr/local/lib/python3.9/dist-packages
/usr/lib/python3/dist-packages
/usr/lib/python3.9/dist-packages
/home/toni/.local/share/QGIS/QGIS3/profiles/default/python
/home/toni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/extlibs_linux

**Comment by saberraz** [comment]
After QGIS 3.30 LTR release, this is still present.

**Comment by gangerang** [comment]
Can confirm not working on 3.30

**Comment by antoniusz** [comment]
Fixed
